servers :
  main:
    host: example.com
    port: 22
    user: username
    password: password
  other:
    host: other.example.com
    port: 22
    user: otherUsername
    password: somePassword

index:
  host: 127.0.0.1
  dbname: sftp_index
  user: sftp_index
  password: ~